### ISSUE TITLE
The batch size is exceeding the limit provided. Unable to train.

### ISSUE THREAD

**Issue by revsi** [kevinkwl/AoAReader#1]
Traceback (most recent call last):
  File "train.py", line 224, in <module>
    main()
  File "train.py", line 221, in main
    trainModel(model, train_dataset, valid_dataset, optimizer)
  File "train.py", line 152, in trainModel
    train_loss, train_acc = trainEpoch(epoch)
  File "train.py", line 117, in trainEpoch
    pred_answers, answer_probs = model(batch_docs, batch_docs_len, doc_mask, batch_querys, batch_querys_len, query_mask,answers=batch_answers, candidates=candidates)
  File "-/ulti3/lib/python3.5/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "-/-/a-o-a/AoAReader/aoareader/AoAReader.py", line 91, in forward
    alpha = softmax_mask(M, M_mask, axis=1)
  File "-/-/a-o-a/AoAReader/aoareader/AoAReader.py", line 22, in softmax_mask
    shift = shift.expand_as(input).cuda()
  File "-/ulti3/lib/python3.5/site-packages/torch/autograd/variable.py", line 725, in expand_as
    return Expand.apply(self, (tensor.size(),))
  File "-/ulti3/lib/python3.5/site-packages/torch/autograd/_functions/tensor.py", line 111, in forward
    result = i.expand(*new_size)
RuntimeError: The expanded size of the tensor (832) must match the existing size (64) at non-singleton dimension 1. at /pytorch/torch/lib/THC/generic/THCTensor.c:323

**Comment by kevinkwl** [comment]
Hi revsi, can you tell me under what condition the error occurs? At the beginning of the training or at some middle stage?
seems that the batch dimension and document-words dimension are misplaced.  I locally tried batch size 64, it works.

**Comment by revsi** [comment]
I found two bugs in the code.
Line 134 of preprocess.py 
    train_data, valid_data, test_data = Parallel(n_jobs=2)(delayed(vectorize_stories)(stories, vocab_dict)
                                                for stories in [train_stories, valid_stories, **test_stories**]) 
    #test_stories is missing

Line 187 of train.py
       train_data = **torch.load(opt.traindata)** 
  #traindata instead of data

Even After that I get following error

TypeError: torch.index_select received an invalid combination of arguments - got (torch.cuda.FloatTensor, int, torch.LongTensor), but expected (torch.cuda.FloatTensor source, int dim, torch.cuda.LongTensor index).


I tried changing all torch.Longtensor to torch.cude.Longtensor but then encountered that batch size issue.

Can you please update the repository with the local version of your code. Thanks in advance.

**Comment by kevinkwl** [comment]
Thx for pointing out the bugs, I've fixed them and tried the latest repo, which worked. I didn't encountered the batch size issue. 
Which version of pytorch are you using? Mine is 0.1.12_2.😀

**Comment by revsi** [comment]
Thanks for the quick fix. I am using 0.2.0_3 version of pytorch. I am still facing the same issue. What are the parameters you are using for training.

**Comment by kevinkwl** [comment]
The default value in code

**Comment by revsi** [comment]
Check the pull request. fixed the version issue.
